version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: devops/Dockerfile
    container_name: my-flask-app-dc
    restart: unless-stopped
    networks:
      - scalian_training
    environment:
      DB_USER: root
      DB_PWD: rootpwd
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knights
    depends_on:
      - db
    ports:
      - "5001:5000"

  db:
    image: postgres:16-alpine
    container_name: my-flask-app-db
    restart: always
    ports:
      - "32000:5432"
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
      POSTGRES_DB: knights
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      scalian_training:

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/knights
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=rootpwd
      - SONARQUBE_JVM_OPTS=-Xmx2g -Xms1g  # Ajusta la memoria para SonarQube
    networks:
      - scalian_training

  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    environment:
      - RUNNER_NAME=local-runner
      - RUNNER_WORKDIR=/tmp/github-runner
      - RUNNER_GROUP=Default
    volumes:
      - ./github-runner:/tmp/github-runner
    networks:
      - scalian_training

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--httpPort=8080
    ports:
      - "8080:8080"
      - "50000:50000"  # Puerto para la comunicación con los agentes de Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    networks:
      - scalian_training

networks:
  scalian_training:
    driver: bridge

volumes:
  dbdata:
  jenkins_home: